name: char_app
description: "A new Flutter project."
publish_to: 'none' # Prevents accidental publishing to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  modal_progress_hud_nsn: ^0.5.0
  cloud_firestore: ^5.4.4
  intl: ^0.18.0
  cupertino_icons: ^1.0.6
  firebase_auth: ^5.3.1

dev_dependencies:
  firebase_core: ^3.6.0
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/scholar.png"

flutter:
  uses-material-design: true

  assets:
    - assets/scholar.png

  fonts:
    - family: Pacifico
      fonts:
        - asset: assets/Pacifico-Regular.ttf
