// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCH5bAie5YoQMHz7NgMKwI1Fw_3FKE0Mlc',
    appId: '1:679808034837:web:ee4e6e442109fbffed061c',
    messagingSenderId: '679808034837',
    projectId: 'char-app-9b093',
    authDomain: 'char-app-9b093.firebaseapp.com',
    storageBucket: 'char-app-9b093.appspot.com',
    measurementId: 'G-S9S8PTRRYS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChlVjq-OyUQq3lxxGGY0CvDcNI08ZjKDo',
    appId: '1:679808034837:android:21e040df9a17e5d6ed061c',
    messagingSenderId: '679808034837',
    projectId: 'char-app-9b093',
    storageBucket: 'char-app-9b093.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-BF1XCwgE9ws0cNwFfJWlr3INz9bmZhk',
    appId: '1:679808034837:ios:fa874941b4501247ed061c',
    messagingSenderId: '679808034837',
    projectId: 'char-app-9b093',
    storageBucket: 'char-app-9b093.appspot.com',
    iosBundleId: 'com.example.charApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC-BF1XCwgE9ws0cNwFfJWlr3INz9bmZhk',
    appId: '1:679808034837:ios:fa874941b4501247ed061c',
    messagingSenderId: '679808034837',
    projectId: 'char-app-9b093',
    storageBucket: 'char-app-9b093.appspot.com',
    iosBundleId: 'com.example.charApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCH5bAie5YoQMHz7NgMKwI1Fw_3FKE0Mlc',
    appId: '1:679808034837:web:5e9649365d28b0beed061c',
    messagingSenderId: '679808034837',
    projectId: 'char-app-9b093',
    authDomain: 'char-app-9b093.firebaseapp.com',
    storageBucket: 'char-app-9b093.appspot.com',
    measurementId: 'G-CFJKMEQT02',
  );
}
